# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1240, 868)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("py-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbtnDetectOb = QtWidgets.QPushButton(self.centralwidget)
        self.pbtnDetectOb.setGeometry(QtCore.QRect(980, 680, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pbtnDetectOb.setFont(font)
        self.pbtnDetectOb.setObjectName("pbtnDetectOb")
        self.pbtnOpenIm = QtWidgets.QPushButton(self.centralwidget)
        self.pbtnOpenIm.setGeometry(QtCore.QRect(980, 750, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pbtnOpenIm.setFont(font)
        self.pbtnOpenIm.setObjectName("pbtnOpenIm")
        self.lblPicture = QtWidgets.QLabel(self.centralwidget)
        self.lblPicture.setGeometry(QtCore.QRect(20, 10, 891, 801))
        self.lblPicture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblPicture.setText("")
        self.lblPicture.setScaledContents(True)
        self.lblPicture.setObjectName("lblPicture")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(940, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.twDetectedClasses = QtWidgets.QTableWidget(self.centralwidget)
        self.twDetectedClasses.setGeometry(QtCore.QRect(940, 60, 271, 591))
        self.twDetectedClasses.setObjectName("twDetectedClasses")
        self.twDetectedClasses.setColumnCount(0)
        self.twDetectedClasses.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 26))
        self.menubar.setObjectName("menubar")
        self.menuDetectionableClasses = QtWidgets.QMenu(self.menubar)
        self.menuDetectionableClasses.setObjectName("menuDetectionableClasses")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionThere_are_80_possible_objects_that_you_can_detect_with_the_ObjectDetection_class_and_they_are_as_seen_below_person_bicycle_car_motorcycle_airplane_bus_train_truck_boat_traffic_light_fire_hydrant_stop_sign_parking_meter_bench_bird_cat_dog_horse_sheep_cow_elephant_bear_zebra_giraffe_backpack_umbrella_handbag_tie_suitcase_frisbee_skis_snowboard_sports_ball_kite_baseball_bat_baseball_glove_skateboard_surfboard_tennis_racket_bottle_wine_glass_cup_fork_knife_spoon_bowl_banana_apple_sandwich_orange_broccoli_carrot_hot_dog_pizza_donot_cake_chair_couch_potted_plant_bed_dining_table_toilet_tv_laptop_mouse_remote_keyboard_cell_phone_microwave_oven_toaster_sink_refrigerator_book_clock_vase_scissors_teddy_bear_hair_dryer_toothbrush = QtWidgets.QAction(MainWindow)
        self.actionThere_are_80_possible_objects_that_you_can_detect_with_the_ObjectDetection_class_and_they_are_as_seen_below_person_bicycle_car_motorcycle_airplane_bus_train_truck_boat_traffic_light_fire_hydrant_stop_sign_parking_meter_bench_bird_cat_dog_horse_sheep_cow_elephant_bear_zebra_giraffe_backpack_umbrella_handbag_tie_suitcase_frisbee_skis_snowboard_sports_ball_kite_baseball_bat_baseball_glove_skateboard_surfboard_tennis_racket_bottle_wine_glass_cup_fork_knife_spoon_bowl_banana_apple_sandwich_orange_broccoli_carrot_hot_dog_pizza_donot_cake_chair_couch_potted_plant_bed_dining_table_toilet_tv_laptop_mouse_remote_keyboard_cell_phone_microwave_oven_toaster_sink_refrigerator_book_clock_vase_scissors_teddy_bear_hair_dryer_toothbrush.setObjectName("actionThere_are_80_possible_objects_that_you_can_detect_with_the_ObjectDetection_class_and_they_are_as_seen_below_person_bicycle_car_motorcycle_airplane_bus_train_truck_boat_traffic_light_fire_hydrant_stop_sign_parking_meter_bench_bird_cat_dog_horse_sheep_cow_elephant_bear_zebra_giraffe_backpack_umbrella_handbag_tie_suitcase_frisbee_skis_snowboard_sports_ball_kite_baseball_bat_baseball_glove_skateboard_surfboard_tennis_racket_bottle_wine_glass_cup_fork_knife_spoon_bowl_banana_apple_sandwich_orange_broccoli_carrot_hot_dog_pizza_donot_cake_chair_couch_potted_plant_bed_dining_table_toilet_tv_laptop_mouse_remote_keyboard_cell_phone_microwave_oven_toaster_sink_refrigerator_book_clock_vase_scissors_teddy_bear_hair_dryer_toothbrush")
        self.actionDetectionable_classes = QtWidgets.QAction(MainWindow)
        self.actionDetectionable_classes.setObjectName("actionDetectionable_classes")
        self.actionAbout_program = QtWidgets.QAction(MainWindow)
        self.actionAbout_program.setObjectName("actionAbout_program")
        self.actionClose_program = QtWidgets.QAction(MainWindow)
        self.actionClose_program.setObjectName("actionClose_program")
        self.menuDetectionableClasses.addAction(self.actionDetectionable_classes)
        self.menuDetectionableClasses.addAction(self.actionAbout_program)
        self.menuExit.addAction(self.actionClose_program)
        self.menubar.addAction(self.menuDetectionableClasses.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neural network for Image Object Detection"))
        self.pbtnDetectOb.setText(_translate("MainWindow", "Detect objects"))
        self.pbtnOpenIm.setText(_translate("MainWindow", "Open Image"))
        self.label.setText(_translate("MainWindow", "Detected classes"))
        self.menuDetectionableClasses.setTitle(_translate("MainWindow", "Help"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.actionThere_are_80_possible_objects_that_you_can_detect_with_the_ObjectDetection_class_and_they_are_as_seen_below_person_bicycle_car_motorcycle_airplane_bus_train_truck_boat_traffic_light_fire_hydrant_stop_sign_parking_meter_bench_bird_cat_dog_horse_sheep_cow_elephant_bear_zebra_giraffe_backpack_umbrella_handbag_tie_suitcase_frisbee_skis_snowboard_sports_ball_kite_baseball_bat_baseball_glove_skateboard_surfboard_tennis_racket_bottle_wine_glass_cup_fork_knife_spoon_bowl_banana_apple_sandwich_orange_broccoli_carrot_hot_dog_pizza_donot_cake_chair_couch_potted_plant_bed_dining_table_toilet_tv_laptop_mouse_remote_keyboard_cell_phone_microwave_oven_toaster_sink_refrigerator_book_clock_vase_scissors_teddy_bear_hair_dryer_toothbrush.setText(_translate("MainWindow", "There are 80 possible objects that you can detect with the\n"
"ObjectDetection class, and they are as seen below.\n"
"\n"
"    person,   bicycle,   car,   motorcycle,   airplane,\n"
"    bus,   train,   truck,   boat,   traffic light,   fire hydrant,   stop_sign,\n"
"    parking meter,   bench,   bird,   cat,   dog,   horse,   sheep,   cow,   elephant,   bear,   zebra,\n"
"    giraffe,   backpack,   umbrella,   handbag,   tie,   suitcase,   frisbee,   skis,   snowboard,\n"
"    sports ball,   kite,   baseball bat,   baseball glove,   skateboard,   surfboard,   tennis racket,\n"
"    bottle,   wine glass,   cup,   fork,   knife,   spoon,   bowl,   banana,   apple,   sandwich,   orange,\n"
"    broccoli,   carrot,   hot dog,   pizza,   donot,   cake,   chair,   couch,   potted plant,   bed,\n"
"    dining table,   toilet,   tv,   laptop,   mouse,   remote,   keyboard,   cell phone,   microwave,\n"
"    oven,   toaster,   sink,   refrigerator,   book,   clock,   vase,   scissors,   teddy bear,   hair dryer,\n"
"    toothbrush."))
        self.actionDetectionable_classes.setText(_translate("MainWindow", "Detectionable classes"))
        self.actionAbout_program.setText(_translate("MainWindow", "About program"))
        self.actionClose_program.setText(_translate("MainWindow", "Close program"))
